<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AdminLoginTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-05-08T17:00:13</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>cb7bdb33-5d8d-4175-9cda-3c5e1a463f86</testSuiteGuid>
   <testCaseLink>
      <guid>4230cca0-cb52-4d01-aab7-da86b12326da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestAdminLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b070198a-210a-4fe6-848d-1731a9b5ce95</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/AdminLoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>b070198a-210a-4fe6-848d-1731a9b5ce95</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>bb828743-ce2f-45dc-8dd3-cece0313f949</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b070198a-210a-4fe6-848d-1731a9b5ce95</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>f103f4c1-85a7-4328-9b2a-756d71eff93d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
