<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestSuiteIncorrectPassword</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-05-08T16:27:47</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>a24fa966-ae10-47f0-ad4a-367202737bae</testSuiteGuid>
   <testCaseLink>
      <guid>27112b55-190e-430a-b029-2af1ce542a0b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TestIncorrectPasswordNotification</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fb5ade99-533c-4509-9767-5c0ccd1d7346</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestIncorrectPasswordData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>fb5ade99-533c-4509-9767-5c0ccd1d7346</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>6acb88a9-d9e9-4c6d-af16-62dde4aeda9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fb5ade99-533c-4509-9767-5c0ccd1d7346</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>d93d99a9-878f-41ae-9926-835a1d6c6ac7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
